# based on:
# - .github/workflows/ci-test-node.js.yml
# - https://github.com/actions/starter-workflows/blob/b2e786d4e9af21f57ab07c1bc7231ed867f7675f/ci/node.js.yml

name: dist build test

# FUTURE TODO refactor some of the steps into script(s) that
# can be run from either the command line or GitHub CI.

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dist-output:
          - Recompose.cjs.js
          - Recompose.esm.js
          - Recompose.umd.js
        # dist build test of Recompose.min.js is separated into min-dist-build-test.yml
        # due to the number of tests not working with Recompose.min.js

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
          - 16.x
          - 18.x

    defaults:
      run:
        working-directory: build

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build:recompose
      - name: add (--dev) required dependencies
        # FUTURE TODO should install dependencies as specified src/packages/recompose/package.json
        run: yarn add --dev @babel/runtime change-emitter hoist-non-react-statics react-lifecycles-compat
      - name: copy __tests__ from src/packages/recompose
        run: cp -r src/packages/recompose/__tests__ lib/packages/recompose/dist
      - name: copy js files needed for some tests # FUTURE TODO only copy js files **actually** needed here
        run: |
          cp src/packages/recompose/*.js lib/packages/recompose/dist
          cp -r src/packages/recompose/utils lib/packages/recompose/dist
      - name: remove test(s) not working with dist build # FUTURE TODO get all tests working with the dist build
        run: |
          rm lib/packages/recompose/dist/__tests__/mapPropsStream-test.js
          rm lib/packages/recompose/dist/__tests__/mapPropsStreamWithConfig-test.js # issue with Recompose.umd.js
      - run: cp lib/packages/recompose/dist/${{ matrix.dist-output }} lib/packages/recompose/dist/index.js
      - run: yarn jest lib/packages/recompose/dist
